version: 1.2
workflows:
  - name: align_and_count_multiple_report
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/align_and_count_multiple_report.wdl
    testParameterFiles:
      - empty.json
